import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body>
          <SignedIn>
            <NavBar />
            <div>{children}</div>
          </SignedIn>
          <SignedOut>
            <div className="flex items-center justify-center min-h-screen">
              <SignIn routing="hash" /> 
            </div>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
